apiVersion: apply.build/v1alpha1
kind: Service

metadata:
  name: telegram-image-bot

spec:
  build:
    src: .
    env:
      # Можно попробовать указать версию Python здесь, если Apply.Build/Nixpacks это поддерживает.
      # Например, 'NIXPACKS_PYTHON_VERSION': "3.11"
      # Или же NIXPACKS_BUILD_CMD/NIXPACKS_START_CMD, но лучше использовать структуру YAML.
    commands:
      # Команды сборки:
      build:
        - pip install -r requirements.txt # Устанавливаем зависимости

      # Команда запуска: ***ЭТО ИЗМЕНЕНИЕ***
      start:
        - python main.py # Запускаем ваш бот

  resources:
    cpu: 1
    memory: 512Mi

  secrets:
    - key: TELEGRAM_BOT_TOKEN
    - key: MODEL_SCOPE_API_KEY
